### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by levraipixel** [jimmycuadra/jquery-tmpl-rails#5]
Hi,

First, thanks a lot for your amazing job on that gem. I'm using it and it works (almost) like a charm. I just changed the naming of templates not to include folder name in the final name (to allow multiple styles switching) but for all other things its perfect.

I have a suggestion, though, that you may want to look at: I suggest you include helpers in the compilation process. Since templates are quite like views, I often need my helpers and I have to do things like
<% environment.context_class.instance_eval { include ApplicationHelper } %>
on top of every single template I create, which is ok for me but could be done in your gem, I suppose (and maybe with a way not to do it, like an option for instance).

Don't hesitate to challenge me on this.

Yann

**Comment by jimmycuadra** [comment]
Hi Yann,

Thanks for the feedback. Try out the `template-prefix` branch I just pushed as a solution to the template naming issue. You can now do this in `config/application.rb` to have the engine set your templates name to `foo` instead of `templates/foo`:

``` ruby
config.jquery_templates.prefix = "templates"
```

That's assuming the foo template is at `app/assets/javascripts/templates/foo.tmpl`. Basically, set `template_prefix` to whichever part of the logical path you want stripped out. It should behave correctly with or without a trailing slash on the prefix.

As for the helpers issue, what you're doing is not really related to this gem, as ERB processing happens in a separate step, and it's ERB that needs access to the helper methods. You should be able to do this just once in an initializer:

``` ruby
Rails.application.assets.context_class.class_eval { include ApplicationHelper }
```

Let me know if these things take care of your issues. I'll wait to hear back before pushing out a new version of the gem.

**Comment by levraipixel** [comment]
Hi Jimmy,

Thanks for your time on that one. I will try the prefix hack in a few days.
As for the other trick on helpers, it works fine in development but I'm getting errors like

```
rake aborted!
uninitialized constant PealkBackEnd::Application::ApplicationHelper
```

when I rake assets precompile (PealkBackEnd begin my application, of course)
Could you think of a way to solve this one ? I'd understand if you told me it's my business to find out on my own but I've been on this one for hours :(

**Comment by levraipixel** [comment]
and when I try requiring by hand the code and then include it, I got "undefined method" errors so I suppose it means my methods are not included...

**Comment by levraipixel** [comment]
In fact, I really think this is an issue only for templates, since the common solution

```
module Sprockets::Helpers::RailsHelper
    include ApplicationHelper
end
```

works for other asset types

**Comment by jimmycuadra** [comment]
It looks like the environment task is not run by default when running `rake assets:precompile`: https://github.com/rails/sprockets-rails/blob/master/lib/tasks/assets.rake. Try setting `Rails.application.config.assets.initialize_on_precompile = true`. That should boot your environment and load your helpers.

**Comment by levraipixel** [comment]
Thanks for your anwser.
Nope, I've tried that and it doesn't help. By tracking the execution I know that my environment is loaded, so it's not that.

**Comment by jimmycuadra** [comment]
Hmm, it's not immediately obvious to me, then. If you can share your code that might help.

**Comment by levraipixel** [comment]
I will write an as-short-as-possible example from scratch ASAP

**Comment by levraipixel** [comment]
gosh ! it works !
I was doing a silly

```
config.assets.context_class.class_eval
```

in my application.rb, instead of

```
Rails.application.assets.context_class.class_eval
```

in an initializer

Thank you very much for your help !!

**Comment by levraipixel** [comment]
and the prefix solution works, so let's close this issue =)
